-- Cargar lecturas diarias con sus temas, actividades, preguntas reto y respuestas esperadas
insert into lecturas_diarias (fecha, lectura, actividad, tema, pregunta_reto, respuesta_esperada) values
('2026-09-01', '1 Pedro 1–2', 'detective_biblico', 'Esperanza viva y piedra angular', '¿A quiénes llama Pedro la piedra viva desechada por los hombres pero escogida por Dios?', 'Jesucristo'),
('2026-09-02', '1 Pedro 3–4', 'reto_20_segundos', 'Conducta cristiana y sufrimiento', 'Menciona 3 virtudes o actitudes recomendadas por Pedro para la vida cristiana en 1 Pedro 3:8.', 'amor fraternal, misericordia, amabilidad'),
('2026-09-03', 'Ester 1–2', 'completa_idea', 'El banquete del rey y la elección de Ester', 'Completa la frase: Ester hallaba gracia delante de...', 'todos los que la veían'),
('2026-09-04', 'Ester 3–4', 'reto_sorpresa', 'El decreto de Amán y la valentía de Ester', '¿Qué expresión famosa dijo Ester al decidir presentarse ante el rey sin ser llamada?', 'Si perezco, que perezca'),
('2026-09-05', 'Salmos 15 y 24', 'prueba_fuego', 'El ciudadano de Sión y el Rey de gloria', 'Resume los 3 requisitos del Salmo 24:4 para subir al monte del Señor.', '1. Limpio de manos\n2. Puro de corazón\n3. No elevar el alma a cosas vanas ni jurar con engaño'),
('2026-09-07', '1 Pedro 5 y Santiago 1', 'pregunta_aplicacion', 'Humildad y hacedores de la palabra', '¿Qué enseñanza práctica nos deja Santiago 1 sobre ser hacedores y no solo oidores de la palabra?', 'Debemos poner en práctica lo que dice la Palabra de Dios y no solo escucharla engañándonos a nosotros mismos.'),
('2026-09-08', 'Santiago 2–3', 'detective_biblico', 'La fe sin obras y el freno de la lengua', '¿Qué personaje fue justificada por obras cuando recibió a los mensajeros según Santiago 2:25?', 'Rahab'),
('2026-09-09', 'Santiago 4–5', 'reto_20_segundos', 'Sometimiento a Dios y la oración con fe', 'Menciona 3 frutos o cualidades del sabio según Santiago 3:17.', 'pura, pacífica, amable'),
('2026-09-10', 'Ester 5–6', 'completa_idea', 'El cetro de oro y la honra a Mardoqueo', 'Completa la frase de Ester al rey: Si he hallado gracia ante los ojos del rey...', 'se me conceda mi vida por mi petición'),
('2026-09-11', 'Ester 7–8', 'reto_sorpresa', 'La caída de Amán y la salvación de los judíos', '¿En qué lugar fue colgado Amán tras descubrirse su complot?', 'En la horca que él mismo había preparado para Mardoqueo'),
('2026-09-12', 'Salmos 26 y 51', 'prueba_fuego', 'Integridad y oración de arrepentimiento', 'Resume las 3 peticiones principales del Salmo 51:10-12.', '1. Crea en mí un corazón limpio\n2. No me quites tu Santo Espíritu\n3. Devuélveme el gozo de tu salvación'),
('2026-09-14', '1 Tesalonicenses 1–2', 'pregunta_aplicacion', 'Ejemplo de fe y testimonio del evangelio', '¿Qué lección práctica nos da Pablo sobre compartir el evangelio no solo de palabra sino con poder y afecto?', 'Debemos compartir la palabra con amor sincero y ejemplo de vida holy para dar testimonio verdadero.'),
('2026-09-15', '1 Tesalonicenses 3–4', 'detective_biblico', 'Santificación y la venida del Señor', '¿Quién fue enviado por Pablo a Tesalónica para confirmar y confortar a los hermanos en su fe?', 'Timoteo'),
('2026-09-16', '1 Tesalonicenses 5 y 2 Tesalonicenses 1', 'reto_20_segundos', 'Velar en la fe y perseverancia', 'Menciona 3 mandatos breves dados en 1 Tesalonicenses 5:16-18.', 'estad siempre gozosos, orad sin cesar, dad gracias en todo'),
('2026-09-17', 'Ester 9–10', 'completa_idea', 'La fiesta de Purim y la grandeza de Mardoqueo', 'Completa la frase: Los días de Purim debían ser recordados y celebrados por...', 'todas las generaciones'),
('2026-09-18', 'Rut 1–2', 'reto_sorpresa', 'Lealtad de Rut y la provisión en el campo de Booz', '¿Qué le respondió Rut a Noemí cuando esta le pidió que regresara a su pueblo?', 'Tu pueblo será mi pueblo y tu Dios mi Dios'),
('2026-09-19', 'Salmos 101 y 139', 'prueba_fuego', 'Resolución de integridad y la omnisciencia de Dios', 'Resume 3 verdades principales sobre Dios enseñadas en el Salmo 139.', '1. Dios conoce todos nuestros pensamientos y caminos\n2. Su presencia está en todo lugar\n3. Nos formó desde el vientre'),
('2026-09-21', '2 Tesalonicenses 2–3', 'pregunta_aplicacion', 'Firmeza en la verdad y el trabajo digno', '¿Qué enseñanza nos deja 2 Tesalonicenses 3 sobre el trabajo y no cansarnos de hacer el bien?', 'Debemos trabajar con diligencia y no vivir desordenadamente ni cansarnos de hacer el bien.'),
('2026-09-22', 'Judas y 3 Juan', 'detective_biblico', 'Contender por la fe y la hospitalidad', '¿Quién es el personaje elogiado por su fidelidad y amor en 3 Juan?', 'Gayo'),
('2026-09-23', '2 Juan y Filemón', 'reto_20_segundos', 'Andar en verdad y el perdón a Onésimo', 'Menciona 3 virtudes por las cuales Pablo da gracias al recordar a Filemón.', 'amor, fe, bondad'),
('2026-09-24', 'Rut 3–4', 'completa_idea', 'La redención de Rut y el linaje de David', 'Completa la frase de las mujeres a Noemí: Booz ha sido para ti...', 'restaurador de tu alma'),
('2026-09-25', 'Eclesiastés 1–2', 'reto_sorpresa', 'La vanidad de las cosas humanas y la sabiduría', '¿Cuál es la conclusión repetida por el Predicador sobre buscar satisfacción solo en las cosas terrenales?', 'Vanidad de vanidades, todo es vanidad'),
('2026-09-26', 'Salmos 19 y 119:9–16', 'prueba_fuego', 'La gloria de Dios en la creación y la delicia en su palabra', 'Resume los 3 beneficios de la Palabra de Dios explicados en Salmos 19:7-8.', '1. Restaura el alma\n2. Hace sabio al sencillo\n3. Alegra el corazón y alumbra los ojos'),
('2026-09-28', '2 Pedro 1–2', 'pregunta_aplicacion', 'Crecimiento espiritual y advertencia contra falsos maestros', '¿Qué enseñanza práctica nos deja 2 Pedro 1 sobre añadir virtudes a nuestra fe para no estar ociosos?', 'Debemos esforzarnos por añadir a nuestra fe virtud, conocimiento, dominio propio y amor para crecer espiritualmente.'),
('2026-09-29', '2 Pedro 3', 'detective_biblico', 'El día del Señor y los cielos nuevos', '¿Según 2 Pedro 3:8, cuántos años son para el Señor como un solo día?', 'Mil años'),
('2026-09-30', 'Eclesiastés 3–4', 'reto_20_segundos', 'Tiempo para todo y la fuerza del cordón de tres dobleces', 'Menciona 3 tiempos descritos en Eclesiastés 3:1-8.', 'tiempo de nacer, tiempo de plantar, tiempo de reír')
on conflict (fecha) do update set
  lectura = excluded.lectura,
  actividad = excluded.actividad,
  tema = excluded.tema,
  pregunta_reto = excluded.pregunta_reto,
  respuesta_esperada = excluded.respuesta_esperada;